language: python

cache: pip

jobs:
  include:
    # Linux
    - os: linux
      python: 3.6
      dist: xenial
    - os: linux
      python: 3.7
      dist: xenial
    - os: linux
      python: 3.8
      dist: xenial
    - os: linux
      python: 3.9-dev
      dist: xenial
    - os: linux
      python: pypy3
      dist: xenial
    # macOS + PyPy3 + Xcode 12
    - os: osx
      language: generic  # 'language: python' is an error on Travis CI macOS
      osx_image: xcode12
      before_install:
        - brew install git-lfs
        - git lfs install
        - brew install pypy3
        - pip install virtualenv
        - /usr/local/bin/virtualenv -p /usr/local/bin/pypy3 venv
        - source venv/bin/activate
        - python -m pip install --upgrade pytest
        - python -m pip install git+https://github.com/mideind/Tokenizer#egg=tokenizer
      before_script: 
        - git lfs pull
    # macOS + CPython 3.8.2 + Xcode 11
    - os: osx
      language: generic  # 'language: python' is an error on Travis CI macOS
      osx_image: xcode11.6
      before_install:
        - brew install git-lfs
        - git lfs install
        - brew install python@3.8
        - pip install virtualenv
        - /usr/local/bin/virtualenv -p /usr/local/bin/python3.8 venv
        - source venv/bin/activate
        - python -m pip install --upgrade pytest
        - python -m pip install git+https://github.com/mideind/Tokenizer#egg=tokenizer
      before_script: 
        - git lfs pull
    # Windows + CPython 3.7.4
    - os: windows
      language: shell  # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - python -m pip install git+https://github.com/mideind/Tokenizer#egg=tokenizer
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install:
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade pytest
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then python -m pip install mypy; fi
  - python -m pip install git+https://github.com/mideind/Tokenizer#egg=tokenizer

install:
  - python -m pip install -e .

script:
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then mypy src/reynir/__init__.py; fi
  - python -m pytest

notifications:
  slack: greynir:38FfPr1S8oZRNFMmt47mzT3z
